## merge single files to one combined VCF file
sample=($(awk '{print $0}' /home/minc/crypto_data/vcf/strain_name))
for((i=0;i<=(${#sample[@]}-1);i++));do bgzip ${sample[$i]}.real_final.vcf;done
for((i=0;i<=(${#sample[@]}-1);i++));do tabix ${sample[$i]}.real_final.vcf.gz;done
for f in "${sample[@]}"; do sam+=(${f}.real_final.vcf.gz);done
bcftools merge -0 --missing-to-ref -O v --threads 6 -o combined.vcf ${sam[@]}
 
## VCF file to phylip file (alignment)
 ~/biosoft/tasseladmin-tassel-5-standalone-bd304d03e096/run_pipeline.pl -Xmx32g -fork1 -vcf combined.vcf -export scedo_snp -exportType Phylip_Inter -sortPositions -runfork1
 
## building phylogenetic tree using ML with 1000 bootstraps
raxmlHPC-PTHREADS-AVX2  -T 8 -p 1234578 -x 25678 -# 1000 -s crypto_snp.phy -m GTRCAT -f a -n crypto_snp_raxml
